local prefix = "packages.shzl.pkg.god.skills."

return {
  require(prefix .. "wushen"),
  require(prefix .. "wuhun"),
  require(prefix .. "shelie"),
  require(prefix .. "gongxin"),
  require(prefix .. "qinyin"),
  require(prefix .. "yeyan"),
  require(prefix .. "qixing"),
  require(prefix .. "kuangfeng"),
  require(prefix .. "dawu"),
  require(prefix .. "dawu_active"),
  require(prefix .. "kuangbao"),
  require(prefix .. "wumou"),
  require(prefix .. "wuqian"),
  require(prefix .. "shenfen"),
  require(prefix .. "guixin"),
  require(prefix .. "feiying"),
  require(prefix .. "nos_juejing"),
  require(prefix .. "nos_longhun"),
  require(prefix .. "juejing"),
  require(prefix .. "longhun"),
  require(prefix .. "g_juejing"),
  require(prefix .. "g_longhun"),
  require(prefix .. "renjie"),
  require(prefix .. "baiyin"),
  require(prefix .. "lianpo"),
  require(prefix .. "jilue"),
  require(prefix .. "longnu"),
  require(prefix .. "jieying"),
  require(prefix .. "junlue"),
  require(prefix .. "cuike"),
  require(prefix .. "zhanhuo"),
  require(prefix .. "duorui"),
  require(prefix .. "zhiti"),
  require(prefix .. "poxi"),
  require(prefix .. "gn_jieying"),
  require(prefix .. "meihun"),
  require(prefix .. "huoxin"),
}
